language: c

env:
 - GRSEC=true
 - GRSEC=false

before_install:
  - gem install package_cloud
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update || true
  - sudo apt-get install -y gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++

script:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - sudo -E ./buildkernel.sh
